-- ============================================================================
-- setup.sql — GENERATED single-file setup for a fresh Supabase project.
-- Paste this whole file into the Supabase SQL editor and run it once.
-- Generated by concatenating supabase/migrations/*.sql in order.
-- After running it, run the allowlist seed (see the end of this file).
-- NOTE: already applied to the live 'lead-prospector' project via MCP;
-- this file exists for disaster recovery / rebuilding from scratch.
-- ============================================================================

-- ────────────────────────────────────────────────────────────────────────────
-- supabase/migrations/0001_schema.sql
-- ────────────────────────────────────────────────────────────────────────────
-- ============================================================================
-- 0001_schema.sql — enums, tables, indexes
-- ============================================================================

-- Enums -----------------------------------------------------------------------

create type website_tier as enum (
  'none',
  'facebook',
  'instagram',
  'yelp',
  'linktree',
  'google_site',
  'placeholder_builder',
  'real_site'
);

create type pipeline_status as enum (
  'new',
  'contacted',
  'qualified',
  'disqualified',
  'opportunity',
  'customer'
);

create type contact_source as enum (
  'zoominfo',
  'manual'
);

create type activity_outcome as enum (
  'no_answer',
  'left_voicemail',
  'contact',
  'correct_contact',
  'not_interested',
  'bad_data'
);

-- An activity is an "event": a call, a meeting, or a demo.
create type event_type as enum (
  'call',
  'meeting',
  'demo'
);

create type api_call_type as enum (
  'text_search',
  'place_details'
);

-- updated_at helper -----------------------------------------------------------

create or replace function set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- businesses ------------------------------------------------------------------

create table businesses (
  id uuid primary key default gen_random_uuid(),
  place_id text not null unique,           -- dedupe key against Google Places
  name text not null,
  address text,
  phone text,
  category text,                            -- the search category it came from
  rating numeric(2,1),
  review_count int not null default 0,      -- default sort / filter key
  website_uri text,
  website_tier website_tier not null,
  google_maps_uri text,
  pipeline_status pipeline_status not null default 'new',
  disqualify_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index businesses_review_count_idx on businesses (review_count desc);
create index businesses_tier_idx on businesses (website_tier);
create index businesses_status_idx on businesses (pipeline_status);
create index businesses_category_idx on businesses (category);

create trigger businesses_set_updated_at
  before update on businesses
  for each row execute function set_updated_at();

-- contacts --------------------------------------------------------------------

create table contacts (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references businesses (id) on delete cascade,
  name text,
  role text,
  phone text,
  email text,
  source contact_source not null default 'manual',
  notes text,
  created_at timestamptz not null default now()
);

create index contacts_business_idx on contacts (business_id);

-- activities ------------------------------------------------------------------

-- Running log of events on an account (calls, meetings, demos). A call event
-- carries a disposition (outcome); meeting/demo events may leave it null.
-- Notes are always optional.
create table activities (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references businesses (id) on delete cascade,
  logged_by text not null,                  -- email of the user who logged it
  event_type event_type not null default 'call',
  outcome activity_outcome,                 -- required for calls (enforced in app)
  notes text,
  created_at timestamptz not null default now()
);

create index activities_business_idx on activities (business_id, created_at desc);

-- api_usage -------------------------------------------------------------------

create table api_usage (
  id uuid primary key default gen_random_uuid(),
  month text not null,                      -- e.g. '2026-07'
  call_type api_call_type not null,
  count int not null default 0,
  updated_at timestamptz not null default now(),
  unique (month, call_type)
);

-- ────────────────────────────────────────────────────────────────────────────
-- supabase/migrations/0002_rls.sql
-- ────────────────────────────────────────────────────────────────────────────
-- ============================================================================
-- 0002_rls.sql — allowlist + Row Level Security
--
-- Access is locked to an allowlist of exactly the two authorized users.
-- Defense in depth:
--   1. allowed_emails table is the single source of truth.
--   2. A signup trigger BLOCKS any auth.users row whose email isn't allowlisted
--      (rejected at the auth layer, before a session ever exists).
--   3. RLS policies on every table require the JWT email to be allowlisted.
--
-- IMPORTANT: emails are intentionally NOT committed to the repo. After running
-- these migrations, seed the two real addresses (see README, "Seed the
-- allowlist"). Until then, nobody can sign in — which is the safe default.
-- ============================================================================

create table allowed_emails (
  email text primary key,
  created_at timestamptz not null default now()
);

-- Helper: is the *current* authenticated user allowlisted?
create or replace function is_allowed_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from allowed_emails
    where lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

-- --- Auth-layer enforcement --------------------------------------------------
-- Reject any signup whose email is not on the allowlist. Runs before the
-- auth.users row is committed, so a non-allowlisted address can never obtain
-- a session even if RLS were somehow bypassed.
create or replace function enforce_email_allowlist()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1 from allowed_emails where lower(email) = lower(new.email)
  ) then
    raise exception 'Email % is not authorized for this application', new.email
      using errcode = 'insufficient_privilege';
  end if;
  return new;
end;
$$;

create trigger enforce_email_allowlist_on_signup
  before insert on auth.users
  for each row execute function enforce_email_allowlist();

-- --- RLS ----------------------------------------------------------------------

alter table businesses     enable row level security;
alter table contacts       enable row level security;
alter table activities     enable row level security;
alter table api_usage      enable row level security;
alter table allowed_emails enable row level security;

-- businesses: allowlisted users have full read/write.
create policy businesses_all on businesses
  for all to authenticated
  using (is_allowed_user())
  with check (is_allowed_user());

-- contacts
create policy contacts_all on contacts
  for all to authenticated
  using (is_allowed_user())
  with check (is_allowed_user());

-- activities
create policy activities_all on activities
  for all to authenticated
  using (is_allowed_user())
  with check (is_allowed_user());

-- api_usage: readable by allowlisted users (the UI shows the live counter).
-- Writes happen server-side via the service-role key (bypasses RLS), so no
-- write policy is granted to normal users.
create policy api_usage_read on api_usage
  for select to authenticated
  using (is_allowed_user());

-- allowed_emails: allowlisted users may read the roster; no client writes.
create policy allowed_emails_read on allowed_emails
  for select to authenticated
  using (is_allowed_user());

-- ────────────────────────────────────────────────────────────────────────────
-- supabase/migrations/0003_functions.sql
-- ────────────────────────────────────────────────────────────────────────────
-- ============================================================================
-- 0003_functions.sql — atomic API budget-cap RPC
--
-- Every Google API call must reserve a slot BEFORE it is made. This function
-- atomically increments the counter for the current month + call type and
-- refuses (allowed = false) if doing so would exceed the cap. Row-level lock
-- (FOR UPDATE) makes concurrent search runs safe.
--
-- Called only server-side with the service-role key.
-- ============================================================================

create or replace function reserve_api_call(p_call_type api_call_type, p_max int)
returns table (allowed boolean, new_count int)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_month text := to_char(now(), 'YYYY-MM');
  v_count int;
begin
  -- Ensure the row exists, then lock it.
  insert into api_usage (month, call_type, count)
  values (v_month, p_call_type, 0)
  on conflict (month, call_type) do nothing;

  select count into v_count
  from api_usage
  where month = v_month and call_type = p_call_type
  for update;

  if v_count + 1 > p_max then
    -- Deny: would exceed the cap. Counter is left unchanged.
    return query select false, v_count;
    return;
  end if;

  update api_usage
  set count = count + 1, updated_at = now()
  where month = v_month and call_type = p_call_type
  returning count into v_count;

  return query select true, v_count;
end;
$$;

-- Convenience read: current month usage per call type (for the UI badge).
create or replace function current_month_usage()
returns table (call_type api_call_type, count int)
language sql
stable
security definer
set search_path = public
as $$
  select call_type, count
  from api_usage
  where month = to_char(now(), 'YYYY-MM');
$$;

-- ────────────────────────────────────────────────────────────────────────────
-- supabase/migrations/0004_custom_fields.sql
-- ────────────────────────────────────────────────────────────────────────────
-- ============================================================================
-- 0004_custom_fields.sql — user-defined custom fields on businesses
--
-- Custom fields are stored in a JSONB column on `businesses`; their definitions
-- (label, type, options) live in `custom_field_defs`. This lets the leads grid
-- add, sort, filter, and inline/bulk-edit arbitrary fields without schema
-- changes per field.
-- ============================================================================

alter table businesses
  add column custom_fields jsonb not null default '{}'::jsonb;

create table custom_field_defs (
  id uuid primary key default gen_random_uuid(),
  key text not null unique,                 -- stable slug used as the jsonb key
  label text not null,                      -- display name
  type text not null
    check (type in ('text', 'number', 'boolean', 'date', 'select')),
  options jsonb not null default '[]'::jsonb, -- allowed values for 'select'
  created_at timestamptz not null default now()
);

alter table custom_field_defs enable row level security;

create policy custom_field_defs_all on custom_field_defs
  for all to authenticated
  using (is_allowed_user())
  with check (is_allowed_user());

-- Set one custom field to the same value across many businesses (bulk edit) or
-- a single business (inline edit). SECURITY INVOKER, so RLS on `businesses`
-- governs who may write. Passing a JSON null clears the field.
create or replace function set_custom_field(p_ids uuid[], p_key text, p_value jsonb)
returns void
language sql
as $$
  update businesses
  set custom_fields = custom_fields || jsonb_build_object(p_key, p_value)
  where id = any(p_ids);
$$;

-- ────────────────────────────────────────────────────────────────────────────
-- supabase/migrations/0005_activity_stats.sql
-- ────────────────────────────────────────────────────────────────────────────
-- ============================================================================
-- 0005_activity_stats.sql — per-business activity rollups for the leads grid
--
-- Surfaces "last call", "last connect", and "call count" as sortable/filterable
-- columns. security_invoker = on so the existing allowlist RLS on the
-- underlying tables governs access to the view.
-- ============================================================================

create view business_activity_stats
with (security_invoker = on)
as
select
  b.id as business_id,
  max(a.created_at) filter (where a.event_type = 'call') as last_call_at,
  max(a.created_at) filter (
    where a.event_type = 'call'
      and a.outcome in ('contact', 'correct_contact', 'not_interested')
  ) as last_connect_at,
  count(a.id) filter (where a.event_type = 'call')::int as call_count
from businesses b
left join activities a on a.business_id = b.id
group by b.id;

grant select on business_activity_stats to authenticated;

-- ────────────────────────────────────────────────────────────────────────────
-- supabase/migrations/0006_opportunities.sql
-- ────────────────────────────────────────────────────────────────────────────
-- ============================================================================
-- 0006_opportunities.sql — accounts / contacts / opportunities CRM model
--
-- A "lead" (businesses row) is the ACCOUNT. Accounts have many contacts, each
-- contact can carry multiple phone numbers, accounts have many opportunities,
-- and opportunities relate to contacts (many-to-many).
-- ============================================================================

-- Multiple phone numbers per contact (in addition to the primary `phone`).
-- Array of { "label": "...", "number": "..." } objects.
alter table contacts
  add column phones jsonb not null default '[]'::jsonb;

-- Opportunity pipeline stages.
create type opportunity_stage as enum (
  'prospecting',
  'qualification',
  'proposal',
  'negotiation',
  'closed_won',
  'closed_lost'
);

create table opportunities (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references businesses (id) on delete cascade,
  name text not null,
  stage opportunity_stage not null default 'prospecting',
  amount numeric(12, 2),
  close_date date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index opportunities_business_idx on opportunities (business_id);

create trigger opportunities_set_updated_at
  before update on opportunities
  for each row execute function set_updated_at();

-- Many-to-many: which contacts are attached to which opportunities.
create table opportunity_contacts (
  opportunity_id uuid not null references opportunities (id) on delete cascade,
  contact_id uuid not null references contacts (id) on delete cascade,
  role text,
  created_at timestamptz not null default now(),
  primary key (opportunity_id, contact_id)
);

create index opportunity_contacts_contact_idx on opportunity_contacts (contact_id);

-- RLS: allowlisted users only, same as everything else.
alter table opportunities enable row level security;
alter table opportunity_contacts enable row level security;

create policy opportunities_all on opportunities
  for all to authenticated
  using (is_allowed_user())
  with check (is_allowed_user());

create policy opportunity_contacts_all on opportunity_contacts
  for all to authenticated
  using (is_allowed_user())
  with check (is_allowed_user());

-- ────────────────────────────────────────────────────────────────────────────
-- supabase/migrations/0007_function_hardening.sql
-- ────────────────────────────────────────────────────────────────────────────
-- ============================================================================
-- 0007_function_hardening.sql — advisor-driven lockdown of function grants
--
-- - Pin search_path on remaining functions (advisor: function_search_path_mutable)
-- - reserve_api_call: service-role only. It mutates the API budget counter and
--   must never be callable from the browser (anon or authenticated).
-- - current_month_usage / is_allowed_user: authenticated only (the UI badge
--   and RLS policies need them); not anon.
-- - enforce_email_allowlist / set_updated_at: trigger-only, no RPC callers.
-- ============================================================================

alter function set_updated_at() set search_path = public;
alter function set_custom_field(uuid[], text, jsonb) set search_path = public;

revoke execute on function reserve_api_call(api_call_type, int) from public, anon, authenticated;
grant execute on function reserve_api_call(api_call_type, int) to service_role;

revoke execute on function current_month_usage() from public, anon;
grant execute on function current_month_usage() to authenticated, service_role;

revoke execute on function is_allowed_user() from public, anon;
grant execute on function is_allowed_user() to authenticated, service_role;

revoke execute on function enforce_email_allowlist() from public, anon, authenticated;

revoke execute on function set_updated_at() from public, anon, authenticated;

revoke execute on function set_custom_field(uuid[], text, jsonb) from public, anon;
grant execute on function set_custom_field(uuid[], text, jsonb) to authenticated, service_role;

-- ────────────────────────────────────────────────────────────────────────────
-- FINAL STEP — seed the two-user allowlist (REQUIRED: nobody can sign in
-- until this runs). Emails are kept out of this public repo on purpose;
-- replace the placeholders with the two real authorized addresses.
-- ────────────────────────────────────────────────────────────────────────────
-- insert into allowed_emails (email) values
--   ('FIRST_USER_EMAIL'),
--   ('SECOND_USER_EMAIL')
-- on conflict (email) do nothing;
